export const routes = {
  home: "/",
  about: "/about",
  security: "/security",
  inviteCode: "/auth/invite-code",
  login: "/auth/login",
  passkeyRegister: "/auth/passkey/register",
  passkeyVerify: "/auth/passkey/verify",
  mainMenu: "/main-menu",
  settings: "/settings",
  myTokens: "/my-tokens",
  reportCategory: "/report/category",
  reportBasicInfo: "/report/basic-info",
  reportOrganization: "/report/organization",
  reportPerson: "/report/person",
  reportLocation: "/report/location",
  reportOccurrence: "/report/occurrence",
  reportEvidence: "/report/evidence",
  reportContact: "/report/contact",
  reportConfirmation: "/report/confirmation",
  reportSuccess: "/report/success",
  reportFamous: "/report/famous",
  reportManual: "/report/manual",
  myRequests: "/my-requests",
  requestDetail: (id: string) => `/request/${id}`,
  approvalList: "/approval-list",
  inviteUser: "/invite-user",
  register: "/auth/register",
} as const;
