apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    isDefault: true
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: [{ key: "service.name", value: "service_name" }]
      nodeGraph:
        enabled: true

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
