#!/usr/bin/env bash
# Generate secrets.yaml with secure random values.
# Usage: ./daadnegar-chart/scripts/generate-secrets.sh > daadnegar-chart/secrets.yaml
# Then encrypt: sops -e -i daadnegar-chart/secrets.yaml

set -e

DB_ROOT=$(openssl rand -base64 24)
DB_PASS=$(openssl rand -base64 20)
MINIO_USER=$(openssl rand -hex 16)
MINIO_PASS=$(openssl rand -base64 24)
RABBIT_USER=$(openssl rand -hex 12)
RABBIT_PASS=$(openssl rand -base64 20)
BETTER_AUTH=$(openssl rand -base64 32)
BOOTSTRAP=$(openssl rand -base64 24)

# Set YOUR_DOMAIN for production URLs, or leave as placeholder
DOMAIN="${YOUR_DOMAIN:-your-domain.com}"

cat << EOF
# Generated by scripts/generate-secrets.sh - encrypt before committing
# Encrypt: sops -e -i daadnegar-chart/secrets.yaml

database:
  rootPassword: "$DB_ROOT"
  password: "$DB_PASS"
  database: "daadnegar"
  user: "daadnegar"

minio:
  rootUser: "$MINIO_USER"
  rootPassword: "$MINIO_PASS"

rabbitmq:
  user: "$RABBIT_USER"
  password: "$RABBIT_PASS"

env:
  BETTER_AUTH_SECRET: "$BETTER_AUTH"
  BETTER_AUTH_URL: "https://${DOMAIN}"
  BOOTSTRAP_SECRET: "$BOOTSTRAP"
  FRONTEND_URL: "https://${DOMAIN}"
  NEXT_PUBLIC_APP_URL: "https://${DOMAIN}"
  NODE_ENV: "production"
EOF
